# Generated by Django 4.1.4 on 2023-04-19 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('From', models.CharField(max_length=100)),
                ('To', models.CharField(max_length=100)),
                ('pnr_no', models.IntegerField(default=0)),
                ('dept_time', models.CharField(max_length=100)),
                ('rich_time', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('economy_seat', models.IntegerField(default=0)),
                ('pre_economy_seat', models.IntegerField(default=0)),
                ('business_seat', models.IntegerField(default=0)),
                ('first_class_seat', models.IntegerField(default=0)),
                ('economy_seat_price', models.IntegerField(default=0)),
                ('pre_economy_seat_price', models.IntegerField(default=0)),
                ('business_price', models.IntegerField(default=0)),
                ('first_class_seat_price', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('everyday', models.CharField(default='NO', max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='S_flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_type', models.CharField(max_length=25)),
                ('depature', models.CharField(max_length=100)),
                ('arrive', models.CharField(max_length=100)),
                ('depart_date', models.DateTimeField(default=datetime.date(2023, 4, 19))),
                ('return_date', models.DateTimeField(default=datetime.date(2023, 4, 19))),
                ('cabin_class', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('confirm_password', models.CharField(max_length=200)),
            ],
        ),
    ]
