# Generated by Django 4.1.4 on 2023-04-23 05:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_flight',
            name='depart_date',
            field=models.DateTimeField(default=datetime.date(2023, 4, 23)),
        ),
        migrations.AlterField(
            model_name='s_flight',
            name='return_date',
            field=models.DateTimeField(default=datetime.date(2023, 4, 23)),
        ),
        migrations.CreateModel(
            name='travel_passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=255)),
                ('Last_name', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=55)),
                ('Pnr_no', models.CharField(max_length=55)),
                ('Total_price', models.CharField(max_length=55)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
