# Generated by Django 4.1.4 on 2023-04-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_travel_passenger_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.CharField(max_length=255)),
                ('credit_card_number', models.CharField(max_length=255)),
                ('credit_holder_name', models.CharField(max_length=255)),
                ('month_year_expiry', models.DateField()),
                ('cvv_code', models.CharField(max_length=55)),
            ],
        ),
    ]
