place=[
    "Delhi (DEL)",
"Mumbai (BOM)",
"Bengaluru (BLR)",
"Hyderabad (HYD)",
"Chennai (MAA)",
"Kolkata (CCU)",
"Kochi (COK)",
"Los Angeles (LAX)",
"New York (JFK)",
"Chicago (ORD),"
"Atlanta (ATL)",
"Miami (MIA)",
"Dallas/Fort Worth (DFW)",
"San Francisco (SFO)",
"Sydney (SYD)",
"Melbourne (MEL)",
"Brisbane (BNE)",
"Perth (PER)",
"Adelaide (ADL)",
"Darwin (DRW)",
"Cairns (CNS)",
"Moscow (SVO)",
"Saint Petersburg (LED)",
"Sochi (AER)",
"Ekaterinburg (SVX)",
"Novosibirsk (OVB)",
"Kazan (KZN)",
"Vladivostok (VVO)",
"Toronto (YYZ)",
"Vancouver (YVR)",
"Montreal (YUL)",
"Calgary (YYC)",
"Edmonton (YEG)",
"Ottawa (YOW)",
"Halifax (YHZ)",
"Tokyo (HND)",
"Osaka (KIX)",
"Nagoya (NGO)",
"Fukuoka (FUK)",
"Sapporo (CTS)",
"Okinawa (OKA)",
"Sendai (SDJ)",
"Bangkok (BKK)",
"Phuket (HKT)",
"Chiang Mai (CNX)",
"Hat Yai (HDY)",
"Koh Samui (USM)",
"Krabi (KBV)",
"Surat Thani (URT)"
]